name: "idx"
fs:
  indexed_chars: 100%
  lang_detect: true
  continue_on_error: true
  ocr:
    language: "eng"
    enabled: true
    pdf_strategy: "ocr_and_text"
elasticsearch:
  nodes:
    - url: "https://opensearch-node1:9200"  # Update the URL to point to your OpenSearch node
  username: "admin"  # Default OpenSearch admin user, change as necessary
  password: "YourStrongPassword1!"  # Update with the actual password for OpenSearch admin user
  ssl_verification: false  # Set to true and configure properly in production for security
rest:
  url: "http://fscrawler:8080"