---
version: "2.2"


services:
  setup:
    image: opensearchproject/opensearch:latest
    volumes:
      - certs:/usr/share/opensearch/config/certs
    user: "0"
    command: >
      bash -c '
        # Similar setup commands for OpenSearch
      '
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/share/opensearch/config/certs/ca/ca.crt ]"]
      interval: 1s
      timeout: 5s
      retries: 120

  opensearch-node1:
      image: opensearchproject/opensearch:latest
      container_name: opensearch-node1
      environment:
        - cluster.name=opensearch-cluster
        - node.name=opensearch-node1
        - discovery.seed_hosts=opensearch-node1,opensearch-node2
        - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
        - bootstrap.memory_lock=true
        - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
        - compatibility.override_main_response_version=true
        - OPENSEARCH_INITIAL_ADMIN_PASSWORD="YourStrongPassword1!" # Set the admin password
    
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
          hard: 65536
      volumes:
        - opensearch-data1:/usr/share/opensearch/data
      ports:
        - 9200:9200
        - 9600:9600 # required for Performance Analyzer
      networks:
        - opensearch-net

  opensearch-node2:
      image: opensearchproject/opensearch:latest
      container_name: opensearch-node2
      environment:
        - cluster.name=opensearch-cluster
        - node.name=opensearch-node2
        - discovery.seed_hosts=opensearch-node1,opensearch-node2
        - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
        - bootstrap.memory_lock=true
        - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
        - OPENSEARCH_INITIAL_ADMIN_PASSWORD="YourStrongPassword1!"
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      volumes:
        - opensearch-data2:/usr/share/opensearch/data
      networks:
        - opensearch-net




  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
    networks:
      - opensearch-net

  # Update FS Crawler as needed
  fscrawler:
    image: dadoonet/fscrawler:$FSCRAWLER_VERSION
    container_name: fscrawler
    restart: always
    volumes:
      - ../../test-documents/src/main/resources/documents/:/tmp/es:ro
      - ${PWD}/config:/root/.fscrawler
      - ${PWD}/logs:/usr/share/fscrawler/logs
      - /media/oem/12TB/ro:/tmp/es:ro  # Mount your 12TB HDD here
    depends_on:
      - opensearch-node1
    ports:
      - ${FSCRAWLER_PORT}:8080
    command: fscrawler idx --restart --rest
    
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  opensearch-data2:
  certs:
    driver: local
  esdata:
    driver: local
  kibanadata:
    driver: local

networks:
  opensearch-net:
    driver: bridge